version: 2.1
orbs:
  docker: circleci/docker@2.2.0
  gcp-gke: circleci/gcp-gke@1.4.0
  gcr: circleci/gcp-gcr@0.15.0
# jobs:
#   build:
#     docker:
#       - image: circleci/golang:latest
#     working_directory: ~/app
#     steps:
#       - checkout
#       - run:
#           name: Run Build and Test
#           command: |
#             cd hello-cicd
#             ls
#             pwd
#             cd cmd/hellosvc
#             go build .
#             go test -v

  # Build-Push-Image-Docker:
  #   description: Build and push image to Google Container Registry
  #   machine: true
  #   working_directory: ~/app
  #   steps:
  #     - checkout
  #     - gcr/gcr-auth
  #     - gcr/build-image:
  #         path: ./hello-cicd
  #         image: hello-cicd-gke
  #         tag: "v1"
  #     - gcr/push-image:
  #         image: hello-cicd-gke
  #         tag: "v1"
    
  #deploy:
    #description: Deploy application to Google Kubernetes Engine
    #machine: true
    #steps:
      #- gcr/gcr-auth-plugin
      # Install `gcloud` and `kubectl` if not already installed.
      #- gcp-gke/install
      #- gcp-gke/update-kubeconfig-with-credentials:
          #cluster: hello-cicd-gke
      # Initialize the `gcloud` CLI.
      #- gcp-gke/init
      # Update a deployment Docker image.
      #- gcp-gke/rollout-image:
          #cluster: hello-cicd-gke
          #deployment: hello-cicd-gke
          #container: spin-backend
          #image: gcr.io/go-microservice-370513/hello-cicd-gke:v1 # change version when updating
  deploy:
    steps:
      - run:
        command: |
          export USE_GKE_GCLOUD_AUTH_PLUGIN=True
      - gcp-gke/publish-and-rollout-image:
          # requires:
          #   - build
          cluster: hello-cicd-gke
          container: spin-backend
          deployment: hello-cicd-gke
          dockerfile-dir: ./hello-cicd
          image: hello-cicd-gke
          tag: "v1"

workflows:
  build_update_deploy:
    jobs:
      # - build
      # - Build-Push-Image-Docker:
      #     requires:
      #       - build
      # - deploy:
      #     requires:
      #       - Build-Push-Image-Docker

      - deploy
      # - gcp-gke/publish-and-rollout-image:
      #     # requires:
      #     #   - build
      #     cluster: hello-cicd-gke
      #     container: spin-backend
      #     deployment: hello-cicd-gke
      #     dockerfile-dir: ./hello-cicd
      #     image: hello-cicd-gke
      #     tag: "v1"
