apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-cicd-gke
  labels:
    app: simple-backend
spec:
  selector:
    matchLabels:
      app: hello-cicd
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-cicd
        tier: backend
    spec:
      containers:
        - image: gcr.io/go-microservice-370513/hello-cicd-gke:v1
          name: hello-cicd
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 8082
              name: grpc