apiVersion: v1
kind: Service
metadata:
  name: hello-cicd
  labels:
    app: hello-cicd
spec:
  ports:
  - port: 8081
    name: http
    targetPort: 8081
  - port: 8082
    name: grpc
    targetPort: 8082
  selector:
    app: hello-cicd
    tier: backend
  type: LoadBalancer

